[2023-10-09T02:34:40.336+0000] {processor.py:157} INFO - Started process (PID=584) to work on /opt/airflow/dags/scripts/generate_job_dump.py
[2023-10-09T02:34:40.337+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scripts/generate_job_dump.py for tasks to queue
[2023-10-09T02:34:40.338+0000] {logging_mixin.py:151} INFO - [2023-10-09T02:34:40.338+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/generate_job_dump.py
[2023-10-09T02:34:40.460+0000] {logging_mixin.py:151} INFO - [2023-10-09T02:34:40.459+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/scripts/generate_job_dump.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/generate_job_dump.py", line 55, in <module>
    generate_job_dump({"job_title" : "Software Engineer", "job_location" : "United States"})
  File "/opt/airflow/dags/scripts/generate_job_dump.py", line 50, in generate_job_dump
    job_ids = find_job_ids(search_params['job_title'], search_params['job_location'])
  File "/opt/airflow/dags/scripts/generate_job_dump.py", line 13, in find_job_ids
    job_postings = response.json()['data']
KeyError: 'data'
[2023-10-09T02:34:40.462+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/generate_job_dump.py
[2023-10-09T02:34:40.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scripts/generate_job_dump.py took 0.142 seconds
